[build]
  publish = "dist"
  command = "npm run build"

# Proxy API requests to the backend services
[[redirects]]
  from = "/api/User*"
  to = "http://service1.runasp.net/api/User:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/Transaction*"
  to = "http://service2.runasp.net/api/Transaction:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/Report*"
  to = "http://service3.runasp.net/api/Report:splat"
  status = 200
  force = true

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 